# Site settings
defaults:
  -
    scope:
      path: "" # Empty string for all files
    values:
      title: "iScor's Blog" # Default title
      description: Blog about my works and researches in web development # Default meta description
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

feed_description: iScor's Blog - web & mobile development # RSS feed site description
url: "http://iscor.me" # The base hostname & protocol for our site
baseurl: "" # The subpath of our site, e.g. /blog/
twitter_username: iTweetScor
rss_path: feed.xml

# Build settings
markdown: kramdown
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
exclude: [
  'README.md',
  'bower.json',
  'package.json',
  'yarn.lock',
  '.travis.yml',
  'Gem*',
  'Guard*',
  '.jekyll-metadata',
  'scripts',
  '.sass-cache',
  'node_modules'
]
gems: ['jekyll-paginate']

permalink:   /:title
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
timezone:    Europe/Paris

sass:
    style: compressed

figures:
  enumerate: true
