# Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
title: iScor's Blog
email: sebastien.correaud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about my works and researches in web development
baseurl: "" # the subpath of my site, e.g. /blog
url: "http://iscor.me" # the base hostname & protocol for my site, e.g. http://example.com
twitter_username: iTweetScor
github_username:  iGitScor
permalink:   /:title
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
timezone:    Europe/Paris

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - scripts
  - .travis.yml
